server:
  port: 8222

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      -  id: service-edu
         uri: lb://service-classroom
         predicates: Path=/rabbit/classroom/**
      -  id: service-edu
         uri: lb://service-extracurricular
         predicates: Path=/rabbit/extracurricular/**
      -  id: service-edu
         uri: lb://service-back
         predicates: Path=/rabbit/back/**
      -  id: service-edu
         uri: lb://service-acl
         predicates: Path=/rabbit/acl/**

feign:
  sentinel:
    enabled: true

