server:
  port: 3002
spring:
  application:
    name: service-acl
  datasource:
    url: jdbc:mysql://localhost:3306/springthunder?serverTimezone=Asia/Shanghai
    username: root
    password: Vanessa1020Ives
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.33.128
    password: Vanessa1020Ives
    port: 6279
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #下划线转驼峰
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl  # 日志打印
  type-aliases-package: icu.junyao.acl.entity.**  # *Mapper.xml里resultType的类型别名
  mapper-locations: classpath*:icu/junyao/acl/mapper/*Mapper.xml
  global-config:
    db-config:
      table-prefix: t_  # 去除表名前缀
      id-type: assign_id  # id生成策略


