spring:
  application:
    name: service-back
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

jwt:
  key: h9twhcGnjjwIDxCH
  refresh-key: xT5dZLiZUa7Oe4cP

aliyun:
  vod:
    file:
#      keyId: LTAI5tDv9y5SMuXmJFm86S4v
      keyId: 0
#      keySecret: EYtrPskQ3gNScwvQRLocCUgQWbD76K
      keySecret: 0
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
#      keyId: LTAI5tDv9y5SMuXmJFm86S4v
      keyId: 1
#      keySecret: EYtrPskQ3gNScwvQRLocCUgQWbD76K
      keySecret: 1
      bucketName: junyao-edu


