spring:
  application:
    name: service-back
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB

jwt:
  key: h9twhcGnjjwIDxCH
  refresh-key: xT5dZLiZUa7Oe4cP

aliyun:
  vod:
    file:
      keyId: LTAI5tDv9y5SMuXmJFm86S4v
      keySecret: EYtrPskQ3gNScwvQRLocCUgQWbD76K
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyId: LTAI5tDv9y5SMuXmJFm86S4v
      keySecret: EYtrPskQ3gNScwvQRLocCUgQWbD76K
      bucketName: junyao-edu


